apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-aks-cluster
  annotations:
    github.com/project-slug: kedarbhandare/terraform-aks
    terraform/workspaces: backstage-idp
    terraform/organization: NodeJSAks
  description: Azure Kubernetes Service(AKS) cluster managed by Terraform
  tags:
    - azure
    - aks
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: kedar.bhandare
